#-------------------------------------------------------------------------------#
#            Discover all capabilities of Qodana in our documentation           #
#             https://www.jetbrains.com/help/qodana/about-qodana.html           #
#-------------------------------------------------------------------------------#
#checks for logic errors, unreachable code, potential bugs and the like on pushes and pulls
name: qodana
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "pom.xml"
      - "qodana.yaml"
      - ".github/workflows/qodana.yml"
  pull_request:
    paths:
      - "src/**"
      - "pom.xml"
      - "qodana.yaml"
      - ".github/workflows/qodana.yml"
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2025.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          upload-result: false
          push-fixes: none

